package com.messledger.app.ui.navigation

object Routes {
    const val AUTH = "auth"
    const val HOME = "home"
    const val CREATE_MESS = "create_mess"
    const val JOIN_MESS = "join_mess"
    const val JOIN_MESS_WITH_ID = "join_mess/{messId}"
    const val MESS_DETAIL = "mess_detail/{messId}"
    const val MEMBERS = "members/{messId}"
    const val MEALS = "meals/{messId}"
    const val EXPENSES = "expenses/{messId}"
    const val ADD_EDIT_EXPENSE = "add_edit_expense/{messId}?expenseId={expenseId}"
    const val CONTRIBUTIONS = "contributions/{messId}"
    const val ADD_EDIT_CONTRIBUTION = "add_edit_contribution/{messId}?contributionId={contributionId}"
    const val GUEST_MEALS = "guest_meals/{messId}"
    const val ADD_EDIT_GUEST_MEAL = "add_edit_guest_meal/{messId}?guestMealId={guestMealId}"
    const val ACTIVITY = "activity/{messId}"
    const val MESS_SETTINGS = "mess_settings/{messId}"
    const val PENDING_REQUESTS = "pending_requests/{messId}"
    const val REQUEST_STATUS = "request_status/{messId}"
    
    fun messDetail(messId: String) = "mess_detail/$messId"
    fun members(messId: String) = "members/$messId"
    fun meals(messId: String) = "meals/$messId"
    fun expenses(messId: String) = "expenses/$messId"
    fun addExpense(messId: String) = "add_edit_expense/$messId"
    fun editExpense(messId: String, expenseId: String) = "add_edit_expense/$messId?expenseId=$expenseId"
    fun contributions(messId: String) = "contributions/$messId"
    fun addContribution(messId: String) = "add_edit_contribution/$messId"
    fun editContribution(messId: String, id: String) = "add_edit_contribution/$messId?contributionId=$id"
    fun guestMeals(messId: String) = "guest_meals/$messId"
    fun addGuestMeal(messId: String) = "add_edit_guest_meal/$messId"
    fun editGuestMeal(messId: String, id: String) = "add_edit_guest_meal/$messId?guestMealId=$id"
    fun activity(messId: String) = "activity/$messId"
    fun messSettings(messId: String) = "mess_settings/$messId"
    fun pendingRequests(messId: String) = "pending_requests/$messId"
    fun requestStatus(messId: String) = "request_status/$messId"
    fun joinMessWithId(messId: String) = "join_mess/$messId"
}
